Vagrant.configure("2") do |config|
    servers=[
        {
          :hostname => "control",
          :box => "debian/buster64",
          :ip => "172.16.1.50",
          :ssh_port => '2200'
        },
        {
          :hostname => "node1",
          :box => "debian/buster64",
          :ip => "172.16.1.51",
          :ssh_port => '2201'
        },
        {
          :hostname => "node2",
          :box => "debian/buster64",
          :ip => "172.16.1.52",
          :ssh_port => '2202'
        }
      ]

    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box_download_insecure = true
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]
            node.vm.network :private_network, ip: machine[:ip]
            node.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: "ssh"
            node.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", 512]
                vb.customize ["modifyvm", :id, "--cpus", 1]
            end
        end

        if machine[:hostname] == "control"
          config.vm.provision "shell", inline: <<-SHELL
          sudo apt update
          sudo apt install ansible curl git -y
          SHELL
        end
    end
end